app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ndb_api:
    resource: "@NdbApiBundle/Controller/"
    type:     annotation

test_api:
    resource: "@TestApiBundle/Controller/"
    type:     annotation
